import Link from 'next/link'

export default function Terms () {
  return (
    <div className="flex flex-col max-w-screen-md px-8 pt-20 pb-8 items-start">
      <div className="text-gray-200 z-10 space-y-4">
        <h1 className="text-2xl font-bold">Welcome to saxxys.com.</h1>
        <p>This page tells you the terms on which you may use our website saxxys.com, whether as registered user or guest. Please read carefully before use.<br />By using the site, you accept the terms and agree to obey them. If you don&apos;t accept them, please don&apos;t use the site.</p>
        <p>We reserve the right to remove/reject content that we deem unacceptable, solely at our discretion.<br />Uploaded submissions to the competition must comply to all of our rules, located on the main site, and may be removed at our discretion.</p>
        <p>You have permission for temporary use of the site, but we can withdraw or change our service at any time without telling you and without being legally responsible to you. You must treat all identification codes, passwords and other security information as confidential. If we think you have failed to keep confidentiality, we are allowed to disable any security information (including your passwords and codes).</p>
        <p>You agree to follow our acceptable use policy <Link href="/usepolicy"><a className="text-blue-800">here</a></Link>. If you allow anyone else to use our site, you must make sure that they read these terms first, and that they follow them. Only use the site as allowed by law and these terms. If you don&apos;t, we may suspend your usage, or stop it completely.</p>
        <p>We frequently update the site and make changes to it, but we don&apos;t have to do this, and material on the site may be out-of-date. No material on the site is intended to contain advice, and you shouldn&apos;t rely on it. We exclude all legal responsibility and costs for reliance placed on the site by anyone. We follow our privacy policy in handling information about you. You can read our policy <Link href="/privacypolicy"><a className="text-blue-800">here</a></Link>. By using the site, you agree to us handling this information and confirm that data you provide is accurate.</p>
        <p>If you contact other users of our site or upload material to it, you must follow our acceptable use policy, which sets out standards for usage. You can read this policy <Link href="/usepolicy"><a className="text-blue-800">here</a></Link>. You agree to reimburse us for any costs or expenses we incur as a result of any breach of this term. We won&apos;t be legally responsible to anybody for the accuracy of material that you upload to the site, and we can remove it at any time if we think it doesn&apos;t follow our acceptable use policy.</p>
        <p>If you do anything which is a criminal offence under a law called the Computer Misuse Act 1990, your right to use the site will end straightaway. We will report you to the relevant authorities and give them your identity. Examples of computer misuse include introducing viruses, worms, Trojans and other technologically harmful or damaging material. You mustn&apos;t try to get access to our site or server or any connected database or make any &apos;attack&apos; on the site. We won&apos;t be legally responsible to you for any damage from viruses or other harmful material that you pick up via our site.</p>
        <p>You are allowed to make a legal link to our website&apos;s homepage from your website if the content on your site meets the standards of our acceptable use policy <Link href="/usepolicy"><a className="text-blue-800">here</a></Link>. We can end this permission at any time. You mustn&apos;t suggest any endorsement by us or association with us unless we agree in writing. Links from our Site Platform to other websites are for information only. We don&rsquo;t control them and don&rsquo;t accept responsibility for other websites or any materials found upon them or any loss you suffer from using them.&nbsp;</p>
        <p>We change these terms from time to time and you must check them for changes because they are binding on you.<br />Please email us at communitysaxxys@gmail.com to contact us about any issues.</p>
      </div>
    </div>
  )
}
